development:
  adapter: postgresql
  encoding: unicode
  database: olma_shop_development
  pool: 5
  username: pdr
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: olma_shop_test
  pool: 5
  username: pdr
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: olma_shop_production
  pool: 5
  username: pdr
  password:
